spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test01?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://127.0.0.1:3306/test01?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: ENC(tK8xqlIRBn6Y27AYzUihYg==)
#    username: root
    password: ENC(ULizg8E8GjJfTxzv78vwVg==)

  jackson:
#    time-zone: GMT+8
    time-zone: Asia/Singapore

  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8080
#jasypt:
#  encryptor:
#    password: 123456



# the job-scheduler is enabled by default
# the background-job-server and dashboard are disabled by default
org:
  jobrunr:
    dashboard:
      enabled: true
    background-job-server:
      enabled: true
#    database:
#      skip-create: true
